import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16